/**
 * SQL output formatter.
 * Generates CREATE TABLE + INSERT statements for Postgres, MySQL, and SQLite.
 */

import type { SqlDialect, TableDefinition, FieldType } from "../types";

/**
 * Quote an identifier (table name, column name) for safe SQL output.
 * Postgres/SQLite: double-quote, MySQL: backtick.
 * Escapes the quote character inside the identifier by doubling it.
 */
function quoteIdent(name: string, dialect: SqlDialect): string {
  if (dialect === "mysql") {
    return "`" + name.replace(/`/g, "``") + "`";
  }
  // Postgres & SQLite use double quotes
  return '"' + name.replace(/"/g, '""') + '"';
}

/** Map field types to SQL column types per dialect */
function sqlType(fieldType: FieldType, dialect: SqlDialect): string {
  const typeMap: Record<SqlDialect, Partial<Record<FieldType, string>>> = {
    postgres: {
      uuid: "UUID", id: "SERIAL", boolean: "BOOLEAN",
      integer: "INTEGER", decimal: "NUMERIC", price: "NUMERIC", amount: "NUMERIC",
      datetime: "TIMESTAMPTZ", date: "DATE", time: "TIME", timestamp: "BIGINT",
      age: "INTEGER", rating: "NUMERIC", sequence: "TEXT",
      // ref fields reference UUIDs from other tables
      ref: "UUID",
      // Complex types that return objects/arrays → JSONB in Postgres
      date_range: "JSONB", salary: "JSONB", embedding_vector: "JSONB",
      latitude: "NUMERIC", longitude: "NUMERIC",
    },
    mysql: {
      uuid: "CHAR(36)", id: "INT AUTO_INCREMENT", boolean: "TINYINT(1)",
      integer: "INT", decimal: "DECIMAL(10,2)", price: "DECIMAL(10,2)", amount: "DECIMAL(10,2)",
      datetime: "DATETIME", date: "DATE", time: "TIME", timestamp: "BIGINT",
      age: "INT", rating: "DECIMAL(3,1)", sequence: "VARCHAR(255)",
      // ref fields reference UUIDs from other tables
      ref: "CHAR(36)",
      // Complex types → JSON in MySQL
      date_range: "JSON", salary: "JSON", embedding_vector: "JSON",
      latitude: "DECIMAL(10,8)", longitude: "DECIMAL(11,8)",
    },
    sqlite: {
      uuid: "TEXT", id: "INTEGER", boolean: "INTEGER",
      integer: "INTEGER", decimal: "REAL", price: "REAL", amount: "REAL",
      datetime: "TEXT", date: "TEXT", time: "TEXT", timestamp: "INTEGER",
      age: "INTEGER", rating: "REAL", sequence: "TEXT",
      // ref fields reference UUIDs from other tables
      ref: "TEXT",
      // SQLite has no JSON type — use TEXT (JSON stored as string)
      date_range: "TEXT", salary: "TEXT", embedding_vector: "TEXT",
      latitude: "REAL", longitude: "REAL",
    },
  };

  return typeMap[dialect][fieldType] ?? (dialect === "sqlite" ? "TEXT" : "VARCHAR(255)");
}

/** Return a safe fallback for NOT NULL columns when a generator produced null */
function notNullDefault(fieldType: FieldType): string {
  switch (fieldType) {
    case "id":
    case "integer":
    case "age":
    case "sequence":
    case "timestamp":
      return "0";
    case "decimal":
    case "price":
    case "amount":
    case "rating":
    case "latitude":
    case "longitude":
      return "0.0";
    case "boolean":
      return "FALSE";
    default:
      return "''";
  }
}

/** Escape a value for SQL insertion */
function sqlValue(value: unknown, dialect: SqlDialect): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") {
    if (dialect === "mysql") return value ? "1" : "0";
    if (dialect === "sqlite") return value ? "1" : "0";
    return value ? "TRUE" : "FALSE";
  }
  if (typeof value === "number") return String(value);
  if (typeof value === "object") {
    const json = JSON.stringify(value).replace(/'/g, "''");
    return dialect === "mysql" ? `'${json.replace(/\\/g, "\\\\")}'` : `'${json}'`;
  }
  const str = String(value).replace(/'/g, "''");
  // MySQL interprets backslashes as escape characters by default
  return dialect === "mysql" ? `'${str.replace(/\\/g, "\\\\")}'` : `'${str}'`;
}

export function formatSQL(
  data: Record<string, Record<string, unknown>[]>,
  tables: TableDefinition[],
  dialect: SqlDialect
): string {
  const lines: string[] = [];

  lines.push(`-- Generated by MockHero`);
  lines.push(`-- Dialect: ${dialect}`);
  lines.push(`-- Tables: ${tables.map((t) => t.name).join(", ")}`);
  lines.push("");
  // MySQL uses START TRANSACTION; Postgres/SQLite use BEGIN
  lines.push(dialect === "mysql" ? "START TRANSACTION;" : "BEGIN;");
  lines.push("");

  // Sort tables: parents before children (use same order as data generation)
  const tableOrder = Object.keys(data);

  for (const tableName of tableOrder) {
    const tableDef = tables.find((t) => t.name === tableName);
    if (!tableDef) continue;

    const records = data[tableName];

    // CREATE TABLE
    lines.push(`-- Table: ${tableName}`);
    const columns = tableDef.fields.map((f) => {
      const type = sqlType(f.type, dialect);
      const pk = f.type === "id" ? " PRIMARY KEY" : "";
      const nullable = f.nullable ? "" : " NOT NULL";
      // Don't add NOT NULL to auto-increment columns
      const notNull = f.type === "id" ? "" : nullable;
      return `  ${quoteIdent(f.name, dialect)} ${type}${pk}${notNull}`;
    });

    lines.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(tableName, dialect)} (`);
    lines.push(columns.join(",\n"));
    lines.push(`);`);
    lines.push("");

    // INSERT statements
    if (records.length === 0) continue;

    const fields = tableDef.fields;
    const fieldNames = fields.map((f) => f.name);
    const quotedTable = quoteIdent(tableName, dialect);
    const quotedColumns = fieldNames.map((f) => quoteIdent(f, dialect)).join(", ");

    // Build row values, substituting safe defaults for NOT NULL columns
    // that received null (e.g., when a generator threw an error)
    const rowValues = (record: Record<string, unknown>) =>
      fields.map((f) => {
        const val = record[f.name];
        // If value is null but column is NOT NULL, use a type-appropriate default
        if ((val === null || val === undefined) && !f.nullable && f.type !== "id") {
          return notNullDefault(f.type);
        }
        return sqlValue(val, dialect);
      });

    if (dialect === "sqlite") {
      // SQLite: individual INSERT statements
      for (const record of records) {
        const values = rowValues(record);
        lines.push(
          `INSERT INTO ${quotedTable} (${quotedColumns}) VALUES (${values.join(", ")});`
        );
      }
    } else {
      // Postgres/MySQL: multi-row INSERT (batch in groups of 100)
      for (let i = 0; i < records.length; i += 100) {
        const batch = records.slice(i, i + 100);
        lines.push(`INSERT INTO ${quotedTable} (${quotedColumns}) VALUES`);

        const valueRows = batch.map((record) => {
          const values = rowValues(record);
          return `  (${values.join(", ")})`;
        });

        lines.push(valueRows.join(",\n") + ";");
      }
    }

    lines.push("");
  }

  lines.push("COMMIT;");

  return lines.join("\n");
}
